### ISSUE TITLE
Refactor quiz package

### ISSUE THREAD

**Issue by erykksc** [erykksc/kwikquiz#36]
In quiz package the following changes are needed:
* Use the same template for creating/updating a quiz
* Remove functionality of a quiz preview (go to quiz edit instead)
* Remove Question Order from quizzes, as it should be a lobby setting
* Make Quiz's description optional
* Make Quiz's password optional (can be left empty)
* Questions should have a variable number of answers during creating, not 4 (at least 2 answers are necessary)
* Add functionality to mark multiple answers as correct to a single question

Direct code changes:
* Remove Number field from Question struct
* Remove CorrectAnswer from Question struct
* Remove Number field from Answer struct

**Comment by ducminh02** [comment]
Changes done:
- Remove Question Order from quizzes, as it should be a lobby setting
- Make Quiz's description optional
- Make Quiz's password optional (can be left empty)
- Also fixed a problem with updating quiz which I didn't know we had before
- Remove Number field from Question struct
- Remove Number field from Answer struct

Changes can not be done (or need a very complicated work around). For these changes I have wasted way too much time and found out the problem was with the implementation of JS and HTMX all together makes it very difficult to dynamically change the form to either send PUT or POST request. And it is working at the moment so I want to spend time on building rather than refactoring further

- Use the same template for creating/updating a quiz

This should be kept for now for testing data. Can be removed later when we are done with everything and the create button will direct to create Quikquiz page where we also should have a button to create and edit a quiz

- Remove functionality of a quiz preview (go to quiz edit instead)

Same here, it is working at the moment and it is better to have a slice of index of correctAnswer for later implementation and also I don't want to spend more time changing what is working 

- Remove CorrectAnswer from Question struct

These points are needed but I haven't done them because the frontend team is working on a better version of quiz creation page and I would implement the functionality on it

- **Questions should have a variable number of answers during creating, not 4 (at least 2 answers are necessary)**
- **Add functionality to mark multiple answers as correct to a single question**

And also it would be nice for next time if you write some short points of the changes you added to the quizzes because sometimes I get confused need to spend a lot of time looking into the code again because you added a changed to it
